<?php
/**
 * Localizations for the Kolab SSO plugin
 *
 * Copyright (C) 2018, Kolab Systems AG
 *
 * For translation see https://www.transifex.com/projects/p/kolab/resource/kolab_sso/
 */
$labels['loginby'] = 'Login über $provider';
$labels['errorunknown'] = 'Unbekannter SSO Fehler.';
$labels['errorservererror'] = 'SSO Serverfehler.';
$labels['errorinteractionrequired'] = 'Benutzereingriff notwendig.';
$labels['errorloginrequired'] = 'Benutzer-Authentifizierung notwendig.';
$labels['erroraccountselectionrequired'] = 'Benutzerkonto-Auswahl notwendig.';
